/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package persist;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    
    public static void main(String[] args) {
    	System.out.println("harsh chaudhary");
    }
    
}
